export let products = [
  {
    title: "Calleras Crossfit",
    price: 12.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291177/productos/guantescrossfit_s6vzbv.png",
    stock: 30,
    category: "crossfit",
    hombre: true,
    mujer: true,
    ninos: false,
    oferta: false,
  },
  {
    title: "Pala de paddle",
    price: 24.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291179/productos/palapaddle_kpoxuc.png",
    stock: 20,
    category: "paddle",
    hombre: true,
    mujer: true,
    ninos: false,
    oferta: true,
  },
  {
    title: "Zapatillas de running",
    price: 29.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291182/productos/zapatillasrunning_dp4dns.png",
    stock: 40,
    category: "running",
    hombre: false,
    mujer: true,
    ninos: false,
    oferta: false,
  },
  {
    title: "Conos de entrenamiento",
    price: 9.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291169/productos/conos_h9xqnz.png",
    stock: 50,
    category: "futbol",
    hombre: true,
    mujer: true,
    ninos: true,
    oferta: false,
  },
  {
    title: "Cuerda para saltar",
    price: 6.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291171/productos/cuerdasaltar_rvlyf6.png",
    stock: 60,
    category: "crossfit",
    hombre: true,
    mujer: true,
    ninos: false,
    oferta: false,
  },
  {
    title: "Gorra para running",
    price: 8.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291174/productos/gorrorunning_mizpwf.png",
    stock: 30,
    category: "running",
    hombre: false,
    mujer: false,
    ninos: true,
    oferta: false,
  },
  {
    title: "Banda elástica",
    price: 5.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291164/productos/bandaelastica_iogbps.png",
    stock: 25,
    category: "crossfit",
    hombre: true,
    mujer: true,
    ninos: true,
    oferta: false,
  },
  {
    title: "Pelota de fútbol de entrenamiento",
    price: 11.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291159/productos/balonentrenamiento_wi4css.png",
    stock: 40,
    category: "futbol",
    hombre: false,
    mujer: false,
    ninos: true,
    oferta: true,
  },
  {
    title: "Calcetines de running",
    price: 3.99,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero aspernatur molestiae accusantium voluptatem quisquam, quaerat esse magni est vitae fugiat animi porro odio a modi itaque nobis repellendus quae maiores!",
    img: "https://res.cloudinary.com/dxtpzbn2l/image/upload/v1713291166/productos/calcetasrunning_dycigd.png",
    stock: 70,
    category: "running",
    hombre: false,
    mujer: true,
    ninos: false,
    oferta: true,
  },
];
